# Generated by Django 5.2.16 on 2026-08-04 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=255)),
                ('titre_profil', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=30, null=True)),
                ('telephone_secondaire', models.CharField(blank=True, max_length=30, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('code_postal', models.CharField(blank=True, max_length=20, null=True)),
                ('pays', models.CharField(blank=True, default='Maroc', max_length=100)),
                ('linkedin', models.URLField(blank=True, max_length=500, null=True)),
                ('portfolio', models.URLField(blank=True, max_length=500, null=True)),
                ('site_web', models.URLField(blank=True, max_length=500, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lieu_naissance', models.CharField(blank=True, max_length=150, null=True)),
                ('nationalite', models.CharField(blank=True, max_length=100, null=True)),
                ('situation_familiale', models.CharField(blank=True, max_length=100, null=True)),
                ('permis_conduire', models.CharField(blank=True, max_length=100, null=True)),
                ('mobilite_geographique', models.CharField(blank=True, max_length=100, null=True)),
                ('disponibilite', models.CharField(blank=True, max_length=100, null=True)),
                ('resume_profil', models.TextField(blank=True, null=True)),
                ('objectif_professionnel', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('fichier_cv', models.FileField(upload_to='cv/')),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('source_cv', models.CharField(default='upload', max_length=50)),
                ('statut_traitement', models.CharField(choices=[('en_cours', 'En cours'), ('traité', 'Traité'), ('erreur', 'Erreur')], default='en_cours', max_length=20)),
            ],
            options={
                'db_table': 'candidat',
                'ordering': ['-date_upload'],
            },
        ),
        migrations.CreateModel(
            name='CentreInteret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=255)),
                ('categorie', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centres_interet', to='candidats.candidat')),
            ],
            options={
                'db_table': 'centre_interet',
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('organisme', models.CharField(blank=True, max_length=255, null=True)),
                ('date_obtention', models.DateField(blank=True, null=True)),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('url_verification', models.URLField(blank=True, max_length=500, null=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='candidats.candidat')),
            ],
            options={
                'db_table': 'certification',
            },
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_competence', models.CharField(max_length=255)),
                ('categorie', models.CharField(blank=True, max_length=100, null=True)),
                ('sous_categorie', models.CharField(blank=True, max_length=100, null=True)),
                ('niveau', models.CharField(blank=True, max_length=100, null=True)),
                ('annees_experience', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competences', to='candidats.candidat')),
            ],
            options={
                'db_table': 'competence',
            },
        ),
        migrations.CreateModel(
            name='Langue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('langue', models.CharField(max_length=100)),
                ('niveau', models.CharField(blank=True, max_length=100, null=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='langues', to='candidats.candidat')),
            ],
            options={
                'db_table': 'langue',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('poste', models.CharField(max_length=255)),
                ('organisme', models.CharField(blank=True, max_length=255, null=True)),
                ('lieu', models.CharField(blank=True, max_length=150, null=True)),
                ('periode', models.CharField(blank=True, max_length=100, null=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('en_cours', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='candidats.candidat')),
            ],
            options={
                'db_table': 'experience',
                'constraints': [models.CheckConstraint(condition=models.Q(('date_fin__isnull', True), ('date_debut__isnull', True), ('date_fin__gte', models.F('date_debut')), _connector='OR'), name='experience_date_fin_apres_date_debut')],
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplome', models.CharField(max_length=255)),
                ('specialite', models.CharField(blank=True, max_length=255, null=True)),
                ('etablissement', models.CharField(blank=True, max_length=255, null=True)),
                ('lieu', models.CharField(blank=True, max_length=150, null=True)),
                ('periode', models.CharField(blank=True, max_length=100, null=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('en_cours', models.BooleanField(default=False)),
                ('niveau', models.CharField(blank=True, max_length=100, null=True)),
                ('mention', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations', to='candidats.candidat')),
            ],
            options={
                'db_table': 'formation',
                'constraints': [models.CheckConstraint(condition=models.Q(('date_fin__isnull', True), ('date_debut__isnull', True), ('date_fin__gte', models.F('date_debut')), _connector='OR'), name='formation_date_fin_apres_date_debut')],
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_projet', models.CharField(max_length=255)),
                ('type_projet', models.CharField(blank=True, max_length=100, null=True)),
                ('technologies', models.TextField(blank=True, null=True)),
                ('url_projet', models.URLField(blank=True, max_length=500, null=True)),
                ('periode', models.CharField(blank=True, max_length=100, null=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('en_cours', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('role', models.CharField(blank=True, max_length=150, null=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projets', to='candidats.candidat')),
            ],
            options={
                'db_table': 'projet',
                'constraints': [models.CheckConstraint(condition=models.Q(('date_fin__isnull', True), ('date_debut__isnull', True), ('date_fin__gte', models.F('date_debut')), _connector='OR'), name='projet_date_fin_apres_date_debut')],
            },
        ),
    ]
