# Generated by Django 5.2.16 on 2026-08-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidats', '0002_alter_candidat_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='poste',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='formation',
            name='diplome',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='formation',
            name='etablissement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formation',
            name='specialite',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projet',
            name='nom_projet',
            field=models.TextField(),
        ),
    ]
